services:
  - type: web
    name: ishlab-chiqarish
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: DATA_SOURCE
        value: mysql
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: arkonproduction_09
      - key: DB_HOST
        value: de.ahost.cloud
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: arconper_readonly
      - key: DB_PASSWORD
        value: "arkon08_trello#jg$9"
      - key: DB_NAME
        value: arconper_arcon
